name       : haskell-th-orphans
version    : 0.3.10
release    : 3
source     :
    - https://hackage.haskell.org/package/th-orphans-0.13.10/th-orphans-0.13.10.tar.gz : 4433573649ccf97e475c58f65eb24af0100a954ce2c801c34b8f53157796c928
license    : BSD-3-Clause
component  : programming.haskell
summary    : Orphan instances for TH datatypes.
description: |
    Orphan instances for TH datatypes.
builddeps  :
    - haskell-cabal-install
    - haskell-syb-devel
    - haskell-th-abstraction-devel
    - haskell-th-reify-many-devel
    - haskell-th-lift-instances-devel
rundeps    :
    - devel:
        - haskell-syb-devel
        - haskell-th-abstraction-devel
        - haskell-th-reify-many-devel
        - haskell-th-lift-instances-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
