name       : haskell-th-orphans
version    : 0.13.5
release    : 2
source     :
    - https://hackage.haskell.org/package/th-orphans-0.13.5/th-orphans-0.13.5.tar.gz : 95644d4b7914317e1dd31095947b8371f1a18be0c09e75f0e29203eb774a25ad
license    : BSD-3-Clause
component  : programming.haskell
summary    : Orphan instances for TH datatypes.
description: |
    Orphan instances for TH datatypes.
builddeps  :
    - haskell-cabal-install
    - haskell-th-reify-many
    - haskell-th-lift-instances
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
